### PR TITLE
Avoid escaped characters in index.html

### PR DESCRIPTION
**Pull request by daddykotex**
The reporter in scala 2.11.12, generates invalid html. This happens because the content of CDATA is escaped when it should not be.

Screen Shot 2019-07-09 at 14 37 48

This is a fix for it. I'm open to suggestion because I'm assuming this is an issue in scala-xml rather than this code. But in the meantime, that would be the fix.

### CODE REVIEW

**Comment by daddykotex** [comment]
Anything might come out of this?

**Comment by plinlor** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by daddykotex** [comment]
Signed

**Pull request closed without merging**
