### PR TITLE
Add scala-parser-combinators for PagedSeq

### PR DESCRIPTION
**Pull request by ashawley**
Fixes #1356.

### CODE REVIEW

**Comment by cheeseng** [comment]
@ashawley a quick question to confirm, did you just copy over the latest scala-parser-combinators code?  It so I think it should work.  :)

**Comment by guersam** [comment]
Can I cherry-pick this commit on #1369? Or you can wait for or rebase onto #1378 to fix the build.

**Comment by guersam** [comment]
#1378 is the blocker and the following issues come together:
- Bump scala to 2.13.0-M4
- Bump scalacheck to 1.14.0
- Fix `PagedSeq` suites

**Comment by ashawley** [comment]
> did you just copy over the latest scala-parser-combinators code?

Yes, I'm adding it back as a dependency.  It is one of the newer versions that includes `PagedSeq`

**Comment by ashawley** [comment]
> Can I cherry-pick this commit on 1369?

It's still a work in progress, but like everyone else I'm also blocked by #1380.

**Comment by ashawley** [comment]
I've cherry-picked the work-around for 2.13.0-M4 in 45620ee from #1383.

**Pull request closed without merging**
