### PR TITLE
Bump scalacheck version to 1.14.0

### PR DESCRIPTION
**Pull request by guersam**
Not using new features, just version bump due to the binary incompatibility.

### CODE REVIEW

**Comment by wedens** [comment]
That'd be very useful for downstream dependencies (e.g. https://github.com/typelevel/discipline/issues/52).

**Comment by guersam** [comment]
Bumped to scala 2.13.0-M3 to pass CI. M4 is blocked by https://github.com/rickynils/scalacheck/pull/411.

**Comment by nigredo-tori** [comment]
Regarding the check failures: this happens because Travis switches JDK alternatives before actually installing the package. The fastest solution would probably be adding
```sh
jdk_switcher use $TRAVIS_JDK_VERSION
```
to the beginning of the build script.

Just my two cents to keep this rolling.

**Comment by lrytz** [comment]
scalacheck 1.14.0 for M4 is now on maven central

**Comment by guersam** [comment]
Rebased onto #1378, but probably still need to deal with missing `PagedSeq`. (#1379)

**Comment by guersam** [comment]
Superseded by #1383.

**Pull request closed without merging**
