### PR TITLE
Recognize -S as a valid argument

### PR DESCRIPTION
**Pull request by inmost-light**
Ran into this problem while trying to reproduce a test failure from a property-based test.

### CODE REVIEW

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@inmost-light Thanks for the PR, I forgot to add back in checkArgsForValidity when I resurrected -S in this PR: 

https://github.com/scalatest/scalatest/pull/2104

It is being called by Runner, but not the SBT integration that I tested with.  Thanks for catching it.  :)

**Comment by lionralfs** [comment]
I'm running into the same issue. Has this change been released yet?

**Comment by cheeseng** [comment]
@lionralfs Unfortunately not yet, though the PR is merged.  It should be included in the upcoming 3.2.16.

**Pull request merged**
