### PR TITLE
resolve #1201 replace pegdown with flexmark-java

### LINKED ISSUE #1201: Remove dependency on deprecated pegdown to generate html reports.
Scalatest has a dependency on pegdown to generate html reports. Given that pegdown is deprecated, can we start supporting flexmark-java ?

https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/tools/HtmlReporter.scala#L35

### PR DESCRIPTION
**Pull request by fancywriter**

### CODE REVIEW

**Comment by legopiraat** [comment]
Hi,
Will this be included in the 3.1.x release?

**Comment by anthonyemerson** [comment]
Bumping this in hopes for an ETA on this update? Pegdown is actively breaking builds for me while trying to update my other dependencies

**Comment by fancywriter** [comment]
Some tests fail with.
```
[error] (genRegularTests1/test:testQuick) java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
```

Perhaps I have to look into it and add some dependencies to the class path...

**Comment by fancywriter** [comment]
Something with wrong with travis-ci - this time it fails not because of my change...
https://github.com/travis-ci/travis-ci/issues/9713

Have tried workaround from there but it didn't help me. :-(

**Comment by fancywriter** [comment]
```[error] Server access Error: Received fatal alert: protocol_version url=https://repo1.maven.org/maven2/org/apache/pdfbox/xmpbox/2.0.8/xmpbox-2.0.8.pom```
???

Didn't see such things locally. What can be wrong with travis?

**Comment by fancywriter** [comment]
https://central.sonatype.org/articles/2018/May/04/discontinued-support-for-tlsv11-and-below/ This could be an answer :-(
Maven central on https is no longer supported by JDK6, only by JDK7 or better JDK8.

May be it is a good time to stop supporting JDK6? :-) What do you think?

**Comment by fancywriter** [comment]
Have updated my PR, please merge it.
Travis can't build anything for JDK-6, there is the same issue on current branch too, nothing can be done until #1380 is resolved.

**Comment by anthonyemerson** [comment]
Just going to throw out there that Java 6 is a decade old and even Oracle has finally announced EoS at the end of this year (http://www.oracle.com/technetwork/java/eol-135779.html). Personally I say drop JDK-6 and then we have no issues

**Comment by cheeseng** [comment]
@fancywriter regarding the jdk6 issue, the only reason it is supported in scalatest is that scala 2.10 and 2.11 supports it and scalatest/scalactic supports that 2 scala versions.  Anyway, in the case of Selenium, we're facing the similar issue also (at least in our own test build) as newer selenium released is built on jdk8.  One possible plan is to move the Selenium integration part out as its own project (like Play-ScalaTest integration that we did before) in 3.1, and that new module can be built on jdk8 (or jdk 9/10, following the progress in Selenium), while Scalactic/ScalaTest can still continue to supports jdk6 build until the support for scala 2.10 and 2.11 is dropped.

Anyway, that's my humble opinion, the main decision will be made by @bvenners .

**Comment by anthonyemerson** [comment]
Looks like there is a PR ready that should fix the Travis issue: https://github.com/scalatest/scalatest/pull/1394

**Comment by fancywriter** [comment]
@anthonyemerson, @ashawley I have removed my changes to travis script to avoid conflicts from this pull request, left only what related to the pegdown.

**Comment by fancywriter** [comment]
```
java.lang.UnsupportedClassVersionError: com/vladsch/flexmark/util/options/DataHolder : Unsupported major.minor version 51.0
```
Afraid flexmark doesn't support java-6 and compiled against java-7. 😞

**Comment by anthonyemerson** [comment]
Just gonna throw out there again, anyone still using Java 6 is not updating their Scala, SSBT or ScalaTest versions either. We should really just let Java 6 die.

**Comment by anthonyemerson** [comment]
@bvenners @cheeseng  Any updates on getting rid of pegdown now the that #1394 has been merged in?

**Comment by anthonyemerson** [comment]
Any updates on the status of this?

**Comment by fancywriter** [comment]
@bvenners this is now building fine on travis, good to merge now, what do you think?

**Comment by tovbinm** [comment]
Can somebody please review?

**Comment by tovbinm** [comment]
Oh , my, this is happening!!

**Comment by fancywriter** [comment]
Any chance seeing it in the next 3.0.8 ? 👀

**Comment by anthonyemerson** [comment]
:point_up: do want!

**Comment by bvenners** [comment]
@fancywriter Can you sign a CLA for this contribution? We'd like to merge it in.

https://www.artima.com/cla/contributorsLicenseAgreement.pdf

Thanks.

**Comment by fancywriter** [comment]
🖊

**Comment by anthonyemerson** [comment]
Any idea when we will get a release with these changes?

**Comment by anthonyemerson** [comment]
@fancywriter I'm trying to get my framework setup to use these changes (using 3.1.0-SNAP13)  and I keep getting "java.lang.NoClassDefFoundError: com/vladsch/flexmark/ast/Node" I've already tried importing flexmark, flexmark-all, and flexmark-util as dependencies in my build.sbt and nothing seems to be fixing this missing class. Any ideas? or any chance you ran into this problem when you were creating this branch?

**Comment by fancywriter** [comment]
@anthonyemerson no, I am afraid not - haven't seen any issues. Which exact version have you tried? Please note that the last one didn't work, it's incompatible (may be need more code changes).
Could you share you example (repo or github gist?)? I will take a look.

**Comment by anthonyemerson** [comment]
I was using 50.4 (latest) switched to 35.10 and everything is working perfectly. so good to know _something_ is screwy with the latest version, but for now it works and ANYTHING is better than pegdown

**Pull request merged**
