### PR TITLE
WiP Towards support for Scala.js 1.x

### PR DESCRIPTION
**Pull request by sjrd**
Let's see whether the CI is as unhappy as my local setup, or whether I did not understand how to run this locally.

In any case, the contents of the PR can be useful for anyone who would like to pick up the support for Scala.js 1.x.

### CODE REVIEW

**Comment by sjrd** [comment]
@cheeseng The only failure seems spurious.

I don't know if the current CI is sufficient to validate much of the Scala.js support.

In any case, the changes in this PR will be necessary before upgrading to Scala.js 1.x. The other change that is required is dropping Rhino (and use Node.js, the default). I have tried that but it seems that some stack-trace-related tests fail in that case. Maybe they're a bit too sensitive?

**Comment by cheeseng** [comment]
@sjrd Currently our CI does not build for scala-js, except the examples for scala-js.

It has been a while back, if my memory serves me right, I tried to run our tests with node.js but it always seems to crash with not enough memory problem, I am curious if your branch is running currently with any settings required for node.js?

Thanks!

**Comment by cheeseng** [comment]
@sjrd One reason scala-js build was not in our CI is that it requires much more memory, e.g. 6G and longer time to build and run (on rhino, which takes more than 50 mins), so in fact we left it out of CI currently simply due to we could work out a way to make it friendly to travis yet.  :)

**Comment by sjrd** [comment]
No you're right. I don't really manage to run `scalatestTestJS/test` with Node.js, which consistently crashes with JS out of memory even with
```scala
      //jsDependencies += RuntimeDOM % "test",
      // Give more memory to Node.js, and deactivate source maps
      jsEnv := {
        import org.scalajs.jsenv.nodejs.NodeJSEnv
        new NodeJSEnv(
            NodeJSEnv.Config()
              .withArgs(List("--max_new_space_size=3000", "--max_old_space_size=3000")))
      },
```
`scalacticTestJS/test` manages to run a bunch of tests, then seems to hang. It uses one of my CPUs 100% but I don't know if it's making any progress.

**Comment by cheeseng** [comment]
@sjrd Got a chance to try running your branch, with --max_old_space_size=3000 it freezed my desktop with 16G memory, I wonder if setting parallelTestExecution := false will help, I shall give it a shot tomorrow morning.

**Comment by cheeseng** [comment]
@sjrd just sharing, scalacticTestJS/test took really long to run on rhino, it will eventually finished but really long, I am trying to recall how long it took in my last run, probably more than an hour I think.

**Comment by cheeseng** [comment]
@sjrd fyi I just submitted a PR to your branch here: 

https://github.com/sjrd/scalatest/pull/1

**Comment by cheeseng** [comment]
@bvenners @sjrd Since this branch now works in node-js env, which runs much faster than rhino, I suggest to merge this branch into 3.1.x at this point.

**Comment by sjrd** [comment]
FWIW, I agree.

After that, I think the only thing blocking the migration to Scala.js 1.0.0-M2 is support from ScalaCheck. See https://github.com/rickynils/scalacheck/pull/375

**Comment by bvenners** [comment]
This is also merged into 3.2.x.

**Comment by sjrd** [comment]
@cheeseng ScalaCheck 1.14.0 has been released with support for Scala.js 1.0.0-M3, which unblocks forward progress on this, i.e., you should now be able to publish a ScalaTest for Scala.js 1.0.0-M3 as well.

**Pull request merged**
