### PR TITLE
Cheeseng feature matchers collected refactor

### PR DESCRIPTION
**Pull request by bvenners**
Make Collected public, since it was being returned from a public field in several case classes.

### CODE REVIEW

**Comment by cheeseng** [comment]
@bvenners Oh, I didn't think of that direction, that way could be better I think, since Collected is public now, would you consider to make its sealed sub classes to public/protected (actually is protected better for Collected?)?  Which may enable user of Matchers to enhance the DSL themselves.

Anyway, I'll test this out with Dotty and it works, shall merge it first.

Thanks!

**Comment by cheeseng** [comment]
@bvenners @jducoeur 

Tested: Both public and protected works on Dotty, what do you think of the idea of making it protected instead of public?

**Comment by bvenners** [comment]
@cheeseng i didn't think of protected. That would be best probably. Go ahead and make that change then assign it back to me. Tnx.

**Comment by cheeseng** [comment]
@bvenners I submitted a PR against your branch here: 

https://github.com/scalatest/scalatest/pull/1532

Thanks!

**Pull request merged**
