### PR TITLE
Fix ~ 50 typos

### PR DESCRIPTION
**Pull request by janekdb**
These commands were used to produce a single file to spellcheck,

  $ cat $(find -name *.scala) >> all-scala.txt

  $ cat all-scala.txt |tr '<>()[].,$/@=&#%+:"`' ' '|tr ' ' '\n'|
      sort|uniq > scala-single.txt

### CODE REVIEW

**Comment by janekdb** [comment]
Is there anything I can do to help to get this merged?

**Comment by bvenners** [comment]
Hi Janek,

Thanks for the PR. Sorry for the delay getting back. We have been really snowed under by the Scala.js support effort. Anyway, we highly appreciate your help, like many other open source projects ScalaTest's project policy requires contributor to sign a CLA first before we can merge in the code, can you please print, sign, scan the following CLA:

http://www.artima.com/cla/contributorsLicenseAgreement.pdf

or for corporation:

http://www.artima.com/cla/corpContributorsLicenseAgreement.pdf

and please send the signed copy to:

cla@artima.com

We apologize for the tedium, we have been wanting to provide a digital way to do it, but unfortunately have not found an opportunity to do it yet.

Thanks.

Bill

**Comment by janekdb** [comment]
Hi Bill,

The CLA has been sent.

Best Regards,
Janek

**Comment by janekdb** [comment]
The build failure is not obviously related to the commit,

```
[error] /home/travis/build/scalatest/scalatest/gentests/MustMatchers4/target/scala-2.10/src_managed/test/scala/genmatchers4/EveryMustContainAllOfSpec.scala:513: could not find implicit value for parameter typeClass1: org.scalactic.enablers.EvidenceThat[String]#CanBeContainedInAggregation[org.scalatest.MustMatchers.ResultOfCollectedAny[org.scalactic.Every[String]]]
[error]         all (toLists) mustNot (contain allOf ("fee", "fie", "foe", "fum"))
```

**Pull request merged**
