### PR TITLE
Avoid polling Scala futures

### PR DESCRIPTION
**Pull request by raboof**
`Futures` contained a `futureValueImpl` which would poll the future, unnecessarily
increasing the running time of the test in the (common) case that the future
completes successfully.

`Futures` is implemented by `ScalaFutures` and `JavaFutures`, where `JavaFutures` had
an override for this method to avoid the polling.

This PR moves the `futureValueImpl` implementation to `ScalaFutures` (since it was
only used there anyway), and removes the need to poll.

This also removes (the need for) `FuturesSpec`, since that mainly tested the polling
mechanism that is now neither used in the Java implementation nor in the Scala one.
The actual logic is tested in `JavaFuturesSpec` and `ScalaFuturesSpec` respectively.

### CODE REVIEW

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@raboof Looks good to me!

Do you mind to sign our CLA?

https://www.artima.com/cla/choose-type

Thanks!

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by raboof** [comment]
> @raboof Looks good to me!

Thanks!

> Do you mind to sign our CLA?

Done!

@cla-bot[bot] check

**Pull request merged**
