### PR TITLE
Fix prettifier not being used for property check

### PR DESCRIPTION
**Pull request by mdedetrich**
So in PR https://github.com/scalatest/scalatest/pull/2155 I fixed the `Prettifier` so that it works on case classes however I noticed that its still not being applied even when using `implicit val prettifier: Prettifier = Prettifier.truncateAt(SizeLimit(10))`, i.e.

```
[info] - basic flow without interruptions using PeriodFromFirst works correctly *** FAILED ***
[info]   TestFailedException was thrown during property evaluation.
[info]     Message: The future returned an exception of type: org.apache.kafka.common.errors.TopicExistsException, with message: Topic '3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__' is marked for deletion..
[info]     Location: (RealS3BackupClientTest.scala:155)
[info]     Occurred when passed generated values (
13:39:34.169 [RealS3GzipCompressionBackupClientSpec-akka.kafka.default-dispatcher-22] WARN  org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-jHvePKjywnEQQhTfazjfZSpazLIKrmT-3, groupId=jHvePKjywnEQQhTfazjfZSpazLIKrmT] Error while fetching metadata with correlation id 2290 : {3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__=LEADER_NOT_AVAILABLE, _.1_5.-9...4..-M-.-4U2__._-._7s.xb-1-11-__M--930.8-Q_.Z_._w6-___6v-.1-__9_T_-_4__6___-_.Y-..C4_Q_-0.2N9__-5._-Y-_5e_-w1.Wg.8_.-.._H36_W-_-2z-3..0_.-__-K-c.--_.._1_fYvB.6.6PP-8K.--_UL36G_0-M.-..LOX--=LEADER_NOT_AVAILABLE}
13:39:34.256 [RealS3BackupClientSpec-akka.actor.default-dispatcher-36] INFO  io.aiven.guardian.kafka.backup.s3.BackupClient - Found previous uploadId: lHgmPlCns3yyHrDaUmHpDuCAmjfbkmut9NjSAIrSxh8lwCUhi81gdNkC9gx8Ey58DdvTmegijAE3RIxu.uqBec4exACMYLdPFZx1KEnYhiv0G5j66tdSKexQhoUrVkJx and bucket: guardian-ghngevysrdtcxcwy-kox-mivpyjhbpyffez--q-pfb-6ax3 with key: 2022-10-22T11:37:50.045Z.json
[info]       arg0 = KafkaDataInChunksWithTimePeriod(List(List(ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,0,Some(Zw==),bXF3SEhRUlRublZ2QVVNVFI=,1,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,1,Some(Zw==),bmtaV0Q=,4,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,2,Some(aQ==),dEFJaGxGd1ZUZE1VRnNKUmhQZGRCZm1EY1NERFJjdWdabmtzaHlTSXFGdENVVU9IdXdvSFBGd1JEdEdOakRVUm9iT1ZLa3pnbG0=,8,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,3,Some(aQ==),SXlFcmc=,15,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,4,Some(Zw==),RFVlcXliS2xaa3pwS1JMcHdST1hQQmJvSXhQQkN2Sk5GamxWc3RXQ253enZHUHB6Qk5zbUJTc3hPWlR4VnFTdHNiV0hncmdob1hMZkxMQUJuWGJDT2xMc3Vhc3J4TWdOdEw=,25,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,5,Some(Zw==),eG1UUEZ6d0VnYVRVakRBdFZZdmNRY0tPa3dVTmJvU0hVSlVBT2Jvc0JIZVNHdEFOa3ZubElYeXZlVmZycXdxQkh6SXVyTXdBREtLWVVGVw==,32,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,6,Some(aQ==),VG5rZ1NudmtOc3FERFljYWdJaFBWSUVFc2VXR1pEdVh3UklDanlMYm1ISXFzSXBiYW5STXJYV3l4cUljZEpRSlZaVnRWRmZ6a0tiSkFyUQ==,33,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,7,Some(aQ==),Y25jTGZUR1dGUkFJd1hKRWhkRFpKYUpvcnh3VQ==,41,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,8,Some(Zw==),dGdEZ0VLT09OcmFZeVN2am5jZ3NxTE9FR2ZOSmplb3hzUmJoR3lwYVlFdkFrbWZwZUdOSEFYa1RWRUtaQlhmTGhNWUZ0R1BXWWdMb2hQWEhkRkhQaWZIdHZZbnJOWFBSdA==,42,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,9,Some(Zw==),a2xsd011eG5ET0dvU0d4U0lxUm9Id1V1cmJVZndseW9aS2RjUndQdXBNRWpyY0dOWnJNa3RFS0h6UWZHVkZZR0hSS091c2t3SWpMbXpQalRKanVWZQ==,52,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,10,Some(Zw==),YXpCbWdi,62,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,11,Some(aQ==),dUltRHpKdmFTSHlka0dsTUhMdXRvZXNCWmFXbmdZSEVyTUFYRkhseWh3eUVGTFBscnBLUW1kZEFYekt5VmRU,72,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,12,Some(Zw==),TkFZdGZDcHR5Vw==,82,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,13,Some(Zw==),S2pjWllsSFNXWVhPTnNVZ3Z2YURwSWt4em5K,91,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,14,Some(Zw==),U3VpQUVXaGJMdG5vZ2VuVkxkUk5XSlFYVXpBcm1kZ2JV,92,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,15,Some(aQ==),UkJJSlZWaEhCUUFHanBUVkVwQ1FIb21lb0pJcXlUSlp1WmhqVHFKekloUWlBbk1saGFvb1B1T3hEaHhjTWZnc3B6T2hNYVZWcWF5ZGFuQ1RZeWNIYg==,93,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,16,Some(aQ==),UEFEQVFIWmRvSVVkb1FUTGJuTXlwUWtPWWpuUnVOSnd6TExlU0lRa3o=,94,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,17,Some(aQ==),WFRReg==,95,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,18,Some(aQ==),akdOckxKSGJUZG16aktqcG90SHdocVFoVnpEeGZZTmZ6bFBISkladw==,96,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,19,Some(aQ==),WUlIQ0V1S3VFYmh6SWh0R2luSmd1QmxvaXNYU2ZSUEVBbHh1Q0tTZ0dNRVJ1VFJLZlJIb1lockdQcm1jZmpEY0ZqdWNHcEVOS2FMRUl2eEZzTEtLblROeGVSRGFXZQ==,97,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,20,Some(aQ==),Y3p1c3dQSWU=,98,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,21,Some(aQ==),UnVhWEdxRUdmRE1mRmlTcnlPeU9zbmZkZFRrUGx1d3R0eHBhck1GTWRWb05RUUV1VEpmRXRZem9XeU5DZlF0Sk11bw==,103,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,22,Some(Zw==),YXV6U2V0alpmT1JYWm1pQllFU01GSUxMVU1XeXlkR0tIeENZelpNdENkSFV4QklJcG1sWHBSbkFzaUVSaGNVVVpXTmRVdHRZa1NwV3VhSkx1bnNqWUVRWVFOZVFMVVQ=,113,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,23,Some(aQ==),RnZBVFVPU3ljakdxdmNSUndVZkxNR1NHb1FrTFVsVEJBZGdqSEpqYmJYZ1BlSWZkQ2RmdUtFUHZXS3BKRkJTZElvTU5wUFF6YXV3SHBCZUZyUUhhZ054,114,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,24,Some(aQ==),SUd3bk5QeGVlbk9FeXdlcmREV05z,124,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,25,Some(aQ==),WU9zYWxVT1pMc0t6QXh1Yk5aZ1luRGVTTHR5WHNJZHhaTGxzR01yaGlla1lQUUVOeXh5TnVIQlhIektvZnFobE1FZVZRdXJOSGtzV1FwaEhBZg==,131,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,26,Some(aQ==),T1lSbWdzUUFFbkFvbmp0SmR2Z0VVWnNOb3lKUEpJSlhwanRhZ2FxWldIWE1rR294V3ZyVXQ=,137,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,27,Some(aQ==),Q1hnTk9nVGNrbnRoVXZKR1BlQkhWalN4ZU5XSElseUVQeG5ZQ1lDd3BLaEhjUU1SSnV1anhjbWhmaU1kUnd3Wnp3ckhkaVhaaXFYcVNRQUxTZm9FaVB6VklUcUg=,138,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,28,Some(Zw==),SmNUa2tpd1NmUUh0SG13aVRmTndlR3ZxWGpK,146,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,29,Some(Zw==),a0R4ZVBRWU5zb0pUUlJpeGFOc3hHZ05pY1lFSnJyQXlERWtzaExFVXNkZXdUd1dxb0Vzbw==,147,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,30,Some(Zw==),ellMbG5CY2FLUFlabHpSWE15Q0RmalQ=,157,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,31,Some(Zw==),a0NQdllVakhtYVlOak5tZnhRYnZBdENFbGhRcmJidWlnRA==,158,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,32,Some(Zw==),dVdMZ3Jma2RHa256RXdtR1hkQ3VmbE9aY29qQWFBbXNXZEtXeExwbEFDcHZ6QmdDTFpDU2lpSGd6WGpBUFNRSnZ1bUdyZmNTVXNWcWlTZGpxaUlz,159,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,33,Some(Zw==),d3V5a0J0VmZZSk9YeWVr,167,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,34,Some(Zw==),VlJVWFBvT0JrVWF2c25BV3J3V2FYdFJnT3NlZktOT1VaWG9GakZZR2FUTkV4YQ==,173,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,35,Some(Zw==),emJVZ25LcXBiRGJuU09tTWZud1NCdXhKckhBUXFGcmdRUW55empFQ0VNc29MZGFGbnFreGFPSVpiQk5qU2F4ZElxUHR4a2tIdFNzaGE=,174,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,36,Some(Zw==),SUZna1JCbVNZY2VlYUpkeGpoTVlNZ0lMY2pQamRBSWZvRGFBalV1cGZac2JJZkZvZWNNWWl3,176,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,37,Some(Zw==),V25RWHdEcklTVEJ3ZXlOSVRrVXliamJtWFN2cWdMSU9Zd3Vtb1ZEZU9LdGNLR2pkeUFoVGhzZ1d1V216ZmphTkdz,177,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,38,Some(aQ==),WXV0bk1td3VxVm5XZ0ltRnRlUW1hWEpPWnhhcVhFamJGZ09jQ0FhWVRkWmhxTlJlbkp1R3pGandSUXBuS1dxTEJJQkFrWkhMY3JIdnh1elJoeXJvY0ZnSFVUYms=,187,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,39,Some(Zw==),d25FWm5iVmZiWGpHRXdFYWp2amZuV3BvTA==,197,CreateTime), ReducedConsumerRecord(3.iT.AAf--_.-2.T.93-58_M._._-_21.F-f-_.._.--.P._X._2_-_y.s_-___--_56_c-_5_-g-x.I---.26y7_j__55b_Z--_d_._9._A1-__-20-r_-5.2_.i99--._w._.--2..__E.92K--.13wt-5_...-1T.--U2Qm_-.-_0o_-_C.s3H.-_6---_w_..--h_..-k23__,0,40,Some(aQ==),ZEtkTFp5ZFVkV1VuSElYZmRVV09tSw==,207,CreateTime)
...
```

This keeps on going for ages, i.e. its not being truncated. This is when using scalatestplus-scalacheck with property based tests. After going through the code I think that I found the culprit is was in `decorateStringToValue`, one of them uses a prettifier but the other completely ignores. Not sure if this is an oversight or if I am looking in the wrong places.

Would also like to add a test for this to verify this but not sure where is the appropriate place to put this.

References: https://github.com/scalatest/scalatest/issues/2174

### CODE REVIEW

**Comment by mdedetrich** [comment]
@cheeseng I have re-opened the PR and also updated it so it targets `3.2.x-new`

**Comment by cheeseng** [comment]
@mdedetrich Both scalatest and scalatest+scalacheck PR fix looks good to me, but I am not sure if they are the cause/only cause for the problem you are trying to address, because both of them should affect scala-js/native build only.  The problem you encounter happens in jvm build also right?

**Comment by mdedetrich** [comment]
> PR fix looks good to me, but I am not sure if they are the cause/only cause for the problem you are trying to address

This specific PR doesn't address my problem since it was JVM but theoretically speaking JS/Native should have the exact same problem due to having the same bug so I repoened it.

**Comment by cheeseng** [comment]
> > PR fix looks good to me, but I am not sure if they are the cause/only cause for the problem you are trying to address
> 
> This specific PR doesn't address my problem since as you pointed out it was JVM but theoretically speaking JS/Native should have the exact same problem due to having the same bug so I re-opened it.

I see, I

**Comment by cheeseng** [comment]
Sorry I accidentally closed this, I didn't realize I closed this until I see your message on gitter.

**Pull request merged**
