### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by tonicebrian**
In Spanish the word `problema` is of masculine gender, so in order to match concordance the documentation should say `Muchos problemas`.

### CODE REVIEW

**Comment by cheeseng** [comment]
Thanks for your effort to help us!  By any chance have you signed before Artima Inc. CLA:

http://www.artima.com/cla/contributorsLicenseAgreement.pdf

or for Corporate:

http://www.artima.com/cla/corpContributorsLicenseAgreement.pdf

Please kindly print, sign and scan back a copy to cla@artima.com, we apologize for any inconvenience caused, we intended to improve the process but somehow it just didn't happen yet.

Thanks again for your hard effort!

Cheers.

**Comment by tonicebrian** [comment]
The process is too much cumbersome for just fixing some typos. Could you add the patch yourself, I don't mind the credit? Otherwise I will just close the PR.

**Comment by plinlor** [comment]
@cla-bot[bot] check

**Comment by tonicebrian** [comment]
Guys you need to think about a more friendly process that doesn't turn away people wanting to help.

**Pull request closed without merging**
