### PR TITLE
Update Dotty macros

### PR DESCRIPTION
**Pull request by travisbrown**
Necessary after [this change](https://github.com/lampepfl/dotty/pull/8061).

Not sure if you want this as a PR but I needed the changes for some local testing.

### CODE REVIEW

**Comment by cheeseng** [comment]
@travisbrown I am trying this out, seems like there are regressions when running scalatest tests (sbt scalatestTestDotty/test): 

```
[info] *** 3 TESTS FAILED ***
[info] AssertionsSpec:
[info] The assert(boolean) method 
[info] - should throw TestFailedException with correct message and stack depth when is used to check l3.exists(false) *** FAILED *** (10 milliseconds)
[info]   Some("condition was false") did not equal Some("ci1.exists(321) was false") (AssertionsSpec.scala:1634)
[info]   Analysis:
[info]   Some(value: "c[ondition] was false" -> "c[i1.exists(321)] was false")
[info] AssertionsSpec:
[info] The assume(boolean) method 
[info] - should throw TestCanceledException with correct message and stack depth when is used to check l3.exists(false) *** FAILED *** (1 millisecond)
[info]   Some("condition was false") did not equal Some("ci1.exists(321) was false") (AssertionsSpec.scala:4363)
[info]   Analysis:
[info]   Some(value: "c[ondition] was false" -> "c[i1.exists(321)] was false")
[info] AssertionsSpec:
[info] The assume(boolean, clue) method 
[info] - should throw TestCanceledException with correct message and stack depth when is used to check l3.exists(false) *** FAILED *** (1 millisecond)
[info]   Some("condition was false, dude") did not equal Some("ci1.exists(321) was false, dude") (AssertionsSpec.scala:5755)
[info]   Analysis:
[info]   Some(value: "c[ondition] was false, dude" -> "c[i1.exists(321)] was false, dude")
```

and got the following error when building scalactic tests (sbt scalacticTestDotty/test): 

```
[error] trait LineNumberHelper cannot be accessed as a member of org.scalatest from class DifferSpec.
[error] trait LineNumberHelper cannot be accessed as a member of org.scalatest from class DifferSpec.
[error] trait LineNumberHelper cannot be accessed as a member of org.scalatest from class DifferSpec.
[error] trait LineNumberHelper cannot be accessed as a member of org.scalatest from class DifferSpec.
[error] trait LineNumberHelper cannot be accessed as a member of org.scalatest from class DifferSpec.
[error] trait LineNumberHelper cannot be accessed as a member of org.scalatest from class DifferSpec.
[error] trait LineNumberHelper cannot be accessed as a member of org.scalatest from class DifferSpec.
[error] trait LineNumberHelper cannot be accessed as a member of org.scalatest from class DifferSpec.
[error] trait LineNumberHelper cannot be accessed as a member of org.scalatest from class DifferSpec.
[error] trait LineNumberHelper cannot be accessed as a member of org.scalatest from class DifferSpec.
```

**Comment by travisbrown** [comment]
@cheeseng I saw those failures show up with the latest update but haven't had time to look at them yet (everything was fine with the `20200123` nightly). Maybe @nicolasstucki would know what's going on at a glance?

**Comment by nicolasstucki** [comment]
@travisbrown you missed the following commit https://github.com/dotty-staging/scalatest/commit/c9a7d5883150fba08942755867b619694aff498e

**Comment by nicolasstucki** [comment]
In case something else is missing, this is the current commits we have added https://github.com/dotty-staging/scalatest/commits/ddf5f3dcaf7c0e7893464a658e71020f2acc942c

**Pull request merged**
