### PR TITLE
Merge 3.1.x into 3.2.x

### PR DESCRIPTION
**Pull request by cheeseng**
Merging changes in 3.1.x into 3.2.x branch, and make tests to pass in both jvm and js.

### CODE REVIEW

**Comment by bvenners** [comment]
Hi @cheeseng,

I merged this to make progress, but we still get these three test failures under 3.2.x. These may be fixed by a later PR.

[info] Run completed in 1 minute, 24 seconds.
[info] Total number of tests run: 18534
[info] Suites: completed 690, aborted 0
[info] Tests: succeeded 18531, failed 3, canceled 11, ignored 50, pending 42
[info] *** 3 TESTS FAILED ***
[info] SpecSpec:
[info] when a test fails 
[info] - should generate NotAllowedException wrapping a non-fatal RuntimeException is thrown inside scope *** FAILED *** (3 milliseconds)
[info]   "Spec[Spec].scala" did not equal "Spec[].scala" (SpecSpec.scala:2637)
[info] TestLocationFunctionPathFunSpec:
[info] A Spec 
[info] - cancel !!! CANCELED !!! (0 milliseconds)
[info]   org.scalatest.exceptions.TestCanceledException was thrown. (LocationFunctionSuiteProp.scala:493)
[info] TestLocationFunctionPathFreeSpec:
[info] Test 
[info] - should cancel !!! CANCELED !!! (0 milliseconds)
[info]   org.scalatest.exceptions.TestCanceledException was thrown. (LocationFunctionSuiteProp.scala:464)
[info] RefSpecSpec:
[info] when a test fails 
[info] - should generate NotAllowedException wrapping a non-fatal RuntimeException is thrown inside scope *** FAILED *** (2 milliseconds)
[info]   "RefSpec[Spec].scala" did not equal "RefSpec[].scala" (RefSpecSpec.scala:2497)
[info] TestCanceledExceptionSpec:
[info] The TestCanceledException 
[info] - should give the proper line on assertResult(1) { 2 } !!! CANCELED !!! (0 milliseconds)
[info]   assertResult(1) { 2 } didn't produce a TestCanceledException (TestCanceledExceptionSpec.scala:162)
[info] TestCanceledExceptionSpec:
[info] The TestCanceledException 
[info] - should give the proper line on assertResult(1, "some message") { 2 } !!! CANCELED !!! (0 milliseconds)
[info]   assertResult(1, "some message") { 2 } didn't produce a TestCanceledException (TestCanceledExceptionSpec.scala:179)
[info] TestCanceledExceptionSpec:
[info] The TestCanceledException 
[info] - should give the proper line on intercept[IllegalArgumentException] {} !!! CANCELED !!! (0 milliseconds)
[info]   intercept[IllegalArgumentException] {} didn't produce a TestCanceledException (TestCanceledExceptionSpec.scala:194)
[info] TestCanceledExceptionSpec:
[info] The TestCanceledException 
[info] - should give the proper line on intercept[IllegalArgumentException] { throw new RuntimeException } !!! CANCELED !!! (1 millisecond)
[info]   intercept[IllegalArgumentException] { throw new RuntimeException } didn't produce a TestCanceledException (TestCanceledExceptionSpec.scala:211)
[info] TestCanceledExceptionSpec:
[info] The TestCanceledException 
[info] - should give the proper line on 1 should === (2) !!! CANCELED !!! (0 milliseconds)
[info]   1 should === 2 didn't produce a TestCanceledException (TestCanceledExceptionSpec.scala:229)
[info] TestCanceledExceptionSpec:
[info] The TestCanceledException 
[info] - should give the proper line on an [IllegalArgumentException] should be thrownBy {} !!! CANCELED !!! (0 milliseconds)
[info]   an [IllegalArgumentException] should be thrownBy {} didn't produce a TestCanceledException (TestCanceledExceptionSpec.scala:247)
[info] TestCanceledExceptionSpec:
[info] The TestCanceledException 
[info] - should give the proper line on an [IllegalArgumentException] should be thrownBy { throw new RuntimeException } !!! CANCELED !!! (0 milliseconds)
[info]   an [IllegalArgumentException] should be thrownBy { throw new RuntimeException } didn't produce a TestCanceledException (TestCanceledExceptionSpec.scala:265)
[info] SpecSpec:
[info] when a test fails 
[info] - should generate NotAllowedException wrapping a non-fatal RuntimeException is thrown inside scope *** FAILED *** (1 millisecond)
[info]   "[Spec]Spec.scala" did not equal "[Ref]Spec.scala" (SpecSpec.scala:2496)

**Comment by bvenners** [comment]
Hi @cheeseng,

One other thing is that there was a compiler error under 2.10, so we need to come up with a build/test matrix script. I will make a ticket for that and submit the script I use, which needs enhancements.

Bill

**Comment by cheeseng** [comment]
Hi @bvenners, 

I just checkout the current 3.2.x and ran: 

sbt clean test

but I didn't see the failing tests that you saw, I suspect it is caused by unclean state again.

**Comment by bvenners** [comment]
Ah, that could be, which means I need to improve the build script. I will submit that as a PR somewhere so you can try it out and see if you can improve it. Not only is it apparently broken, it is also incomplete! It doesn't yet compile the Java script tests.

**Pull request merged**
