### PR TITLE
Noinline higher order functions to speed up compilation in Scala.js

### LINKED ISSUE #1161: Add @noinline for faster Scala.js incremental linking times
It appears that the Scala.js linker tries to inline all `test("") {}` and `in {}` closures from ScalaTest, resulting in slow incremental linking times for large test suites. See related discussion:
https://github.com/scala-js/scala-js/issues/2827#issuecomment-302388572 In summary, it seems that adding `@noinline` to all methods that accept a `testFun: => Any` argument (example diff: https://github.com/dotty-staging/scalatest/commit/2a08a06fac79c991efbb6c59bb8d87466f0f82ed) can speed up incremental linking times for small edits. One informal benchmark from the scalameta/scalameta test suite (~1.000 unit tests) shows a 7x speedup, or 600ms instead of 4.5s.

Would you be open to accepting a PR adding `@noinline` to common methods like `def test{}` and `def in {}`?

### PR DESCRIPTION
**Pull request by exoego**
Closes #1161

I have not measured performance since I do not have testbed for slow compilation on Scala.js.

### CODE REVIEW

**Comment by cheeseng** [comment]
@exoego Sorry for attending late to this, I'll try to measure the gain and see how it is going.

By any chance have you signed before Artima Inc. CLA:

http://www.artima.com/cla/contributorsLicenseAgreement.pdf

or for Corporate:

http://www.artima.com/cla/corpContributorsLicenseAgreement.pdf

Please kindly print, sign and scan back a copy to cla@artima.com, we apologize for any inconvenience caused, we intended to improve the process but somehow it just didn't happen yet.

Thanks again for your hard effort!

Cheers.

**Comment by exoego** [comment]
@cheeseng I sent a copy of signed CLA 📫

**Comment by cheeseng** [comment]
@exoego Received with thanks!  I shall try to benchmark the difference in compile time ASAP.

**Comment by cheeseng** [comment]
@exoego I just did a measurement with the following results in seconds: 

| Run | Without @noinline | With @noinline |
|-------|--------------------------|----------------------|
|     1 |                         416 |                   410 |
|     2 |                         415 |                   417 |
|     3 |                         415 |                   417 |
| Avg |                    415.33 |              414.67 |

The tests was done with scalatestTestJS/test:fastOptJS, and resulting .js files are both 338.1MB.

Unfortunately it looks not very encouraging, I suppose https://github.com/scala-js/scala-js/pull/2964 might have fixed the problem to some extend.

I wonder if the changes are only limit to those that takes => Any ?  Would it have any effect for other higher order function like => Unit (for scope level construct like 'describe' in FunSpec) or => Future[x] (for async suites)?  If it does we may consider adding @noinline for them and retry the measurement.

Fyi @sjrd @bvenners

**Comment by plinlor** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by exoego** [comment]
Closing since no clear benefits

**Pull request closed without merging**
