### PR TITLE
Logic Style Tests Fix

### PR DESCRIPTION
**Pull request by cheeseng**
Fixed broken logic style tests, and added them to travis build.

### CODE REVIEW

**Comment by bvenners** [comment]
Hi Chee Seng,

I get some compiler errors for this one under Scala.js:

```
[error] /Users/bv/nobkp/delus/st-built-for-3.2.x/scalatest.js/target/scala-2.12/src_managed/main/org/scalatest/LogicFunSpec.scala:23: not found: type LogicFunSpecLike
[error] class LogicFunSpec extends LogicFunSpecLike {
[error]                            ^
[error] /Users/bv/nobkp/delus/st-built-for-3.2.x/scalatest.js/target/scala-2.12/src_managed/main/org/scalatest/LogicFunSpec.scala:32: type mismatch;
[error]  found   : org.scalatest.LogicFunSpec
[error]  required: org.scalatest.Suite
[error]   override def toString: String = Suite.suiteToString(None, this)
[error]                                                             ^
[warn] /Users/bv/nobkp/delus/st-built-for-3.2.x/scalatest.js/target/scala-2.12/src_managed/main/org/scalatest/enablers/InspectorAsserting.scala:604: This cat
```

and

```
[warn]                ^
[error] /Users/bv/nobkp/delus/st-built-for-3.2.x/scalatest.js/target/scala-2.12/src_managed/main/org/scalatest/fixture/LogicFunSpec.scala:25: not found: type LogicFunSpecLike
[error] abstract class LogicFunSpec extends LogicFunSpecLike {
[error]                                     ^
[error] /Users/bv/nobkp/delus/st-built-for-3.2.x/scalatest.js/target/scala-2.12/src_managed/main/org/scalatest/fixture/LogicFunSpec.scala:35: type mismatch;
[error]  found   : org.scalatest.fixture.LogicFunSpec
[error]  required: org.scalatest.Suite
[error]   override def toString: String = Suite.suiteToString(None, this)
[error]                                                             ^
[warn] /Users/bv/nobkp/delus/st-built-for-3.2.x/scalatest.js/target/scala-2.12/src_managed/main/org/scalatest/matchers/TypeMatcherMacro.scala:39: abstract type TypeTree in type pattern List[context.universe.TypeTree] (the underlying of List[context.universe.TypeTree]) is unchecked since it is eliminated by erasure
[warn]                typeList: List[TypeTree]
[warn]                          ^
[warn] 13 warnings found
[error] four errors found
[error] (scalatestJS/compile:compileIncremental) Compilation failed
[error] Total time: 26 s, completed May 26, 2018 9:24:52 AM
```

Going to skip it for now. Also I would like to get rid of the "Logic" name, so maybe this is out of date anyway. Let's discuss next time we meet.

Thanks.

Bill

**Comment by cheeseng** [comment]
@bvenners this is ready again, the current 3.2.x is broken actually, I have pulled the latest 3.2.x into my branch and make it work again.

**Comment by cheeseng** [comment]
@bvenners As for getting rid of 'Logic' word, I think we should do that after merging in this PR.

**Comment by bvenners** [comment]
diffs look good to me

**Pull request merged**
