### PR TITLE
Fix `shouldNot typeCheck` syntax for Scala 3

### LINKED ISSUE #2007: `shouldNot typeCheck` syntax is broken on Scala 3
Using Scala 3.0.0-RC2 and ScalaTest 3.2.7:

```scala
import org.scalatest._
import funsuite._
import matchers._

class ShouldNotTypeCheckTest extends AnyFunSuite with should.Matchers {
  test("shouldNot typeCheck syntax should work on Scala 3") {
    "val a: String = 2" shouldNot typeCheck
  }
}
```

```
[error] 7 |    "val a: String = 2" shouldNot typeCheck
[error]   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]   |    The 'shouldNot typeCheck' syntax only works with String literals.
```

https://scastie.scala-lang.org/ZlLFMPXmR5KF0xpYpEuSdA

### PR DESCRIPTION
**Pull request by griggt**
Fixes #2007

### CODE REVIEW

**Comment by SethTisue** [comment]
@bvenners I hope this can make 3.2.9

**Comment by bvenners** [comment]
Tnx @griggt for the fix! @SethTisue We'll look into it pronto.

**Comment by cheeseng** [comment]
@bvenners The changes looks great to me, and I tested it with Scala 3.0.0-RC3 also, too bad we missed this for 3.2.8, do you mind to merge the following first: 

https://github.com/scalatest/scalatest/pull/2009

so that we can create release tag for 3.2.8 and continue to merge this as part of 3.2.9?

Thanks.

**Comment by bvenners** [comment]
@cheeseng will do. Tnx for reviewing!

**Comment by bvenners** [comment]
I'm going to merge this, though shouldNotTypeCheck is not differentiating between a type and a syntax error:

```
scala> "val a: Int dude! = 1" shouldNot typeCheck                                                                             
val res14: org.scalatest.Succeeded.type = Succeeded
```

Same is true for assertTypeError:

```
scala> assertTypeError("val a: Int fred = 42")                                                                                
val res5: org.scalatest.Succeeded.type = Succeeded
```

In Scala 2, for example we get:

```
scala> assertTypeError("val a: Int fred = 42") 
org.scalatest.exceptions.TestFailedException: Expected a type error, but got the following parse error: "identifier expected but '=' found.", for code: val a: Int fred = 42
  ... 35 elided
```

**Comment by griggt** [comment]
The compiler classifies the first example as a type error rather than a parser error:

```
scala 3.0.0-RC3> scala.compiletime.testing.typeCheckErrors("val a: Int dude! = 1")                                                                                  
val res0: List[scala.compiletime.testing.Error] = List(Error(<error Not found: type dude> does not take type parameters,val a: Int dude! = 1,11,Typer), Error(Not found: type dude,val a: Int dude! = 1,11,Typer))
```

which seems be the case in Scala 2 as well:

```
scala 2.13.5> "val a: Int dude! = 1" shouldNot typeCheck
val res3: org.scalatest.Succeeded.type = Succeeded
```

https://scastie.scala-lang.org/R1x2YhdURlimVhv5a5jR9A

---

The second example is correctly identified as a parse error by the `shouldNot typeCheck` implementation in this PR:

```
scala 3.0.0-RC3> "val a: Int fred = 42" shouldNot typeCheck                                                                           
org.scalatest.exceptions.TestFailedException: Expected a type error, but got the following parse error: "an identifier expected, but '=' found", for code: val a: Int fred = 42
  ... 38 elided
```

However I notice that `assertTypeError` (I was unaware of this function) has a separate implementation that was not updated by this PR.  

I'd be happy to open a new PR to fix that as well.

**Comment by bvenners** [comment]
@griggt A PR would be awesome. I now remember sometimes I thought something should be a parse error but it was classified as a type error, though I think I checked each of those in Scala 2. Anyway, a PR would be very helpful. Tnx!

**Pull request merged**
