### PR TITLE
3.3.0-SNAP2

### PR DESCRIPTION
**Pull request by cheeseng**
- Pull changes from 3.2.x.
- Bumped up to use scala-js 1.0.1.

### CODE REVIEW

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
No longer applicable, our main branch have moved forward a lot, closing.

**Pull request closed without merging**
