### PR TITLE
[3.3] Safe/Pure Style Traits

### PR DESCRIPTION
**Pull request by cheeseng**
Please note that this branch is based on the following open PR: 

https://github.com/scalatest/scalatest/pull/2003

Please merge PR #2003 so that the diff here is clearer.

This PR brings back safe/pure style traits.

### CODE REVIEW

**Comment by bvenners** [comment]
@cheeseng Actually the intention is to bring back FunSuite, not add a SafeFunSuite. We can now bring back plain old FunSuite as a style that takes Assertion as its result type, because it has been long enough since we deprecated the old FunSuite and moved folks over to AnyFunSuite. Can you do an update to this PR that changes the SafeX names to just X? Tnx.

**Comment by cheeseng** [comment]
@bvenners Noted, I'll continue to work on this branch to take away the 'Safe' prefix.

**Comment by cheeseng** [comment]
@bvenners I have dropped the 'Safe' prefix, except for SafeTestRegistration and FixtureSafeTestRegistration, do you think we should use 'Pure' for them?

**Comment by bvenners** [comment]
> @bvenners I have dropped the 'Safe' prefix, except for SafeTestRegistration and FixtureSafeTestRegistration, do you think we should use 'Pure' for them?

@cheeseng These were deprecated in 3.1.0 with no replacement planned. I think we should remove them in 3.3.0. If all else looks good in this PR, I'll merge this, and make another ticket for removing the TestRegistration traits. For context, these traits were so people could do certain kinds of integrations without needing to pick a style. But they didn't get used much if at all, so to simplify the API we wanted to just drop them after a deprecation cycle.

**Pull request merged**
