### PR TITLE
Trying Travis for Js, Native and Dotty (DO-NOT-MERGE)

### PR DESCRIPTION
**Pull request by cheeseng**
Trying out travis to build for js, native and dotty.

### CODE REVIEW

**Comment by cheeseng** [comment]
Closing for re-opening for travis build.

**Comment by cheeseng** [comment]
Reopen for travis build.

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
Closing as no longer applicable, we now use github action for CI build.

**Pull request closed without merging**
