### PR TITLE
[3.3.x] Changes from 3.2.0

### PR DESCRIPTION
**Pull request by cheeseng**
Pull latest changes from 3.2.x-new (currently released as 3.2.0) into 3.3.x.

### CODE REVIEW

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Pull request merged**
