### PR TITLE
Issue #1350: Disambiguate wording: eventually, ultimately

### PR DESCRIPTION
**Pull request by giftig**
Also correct two typos of 'future' on adjacent lines which I spotted in
passing.

### CODE REVIEW

**Comment by cheeseng** [comment]
@giftig LGTM, did you get an email about a CLA from us?  Thanks.

**Comment by giftig** [comment]
@cheeseng Hm I just checked my e-mail but don't see one. I'll be happy to have a read of your CLA if you can link me to it or e-mail me.

**Comment by cheeseng** [comment]
@giftig The CLA for individual contributor is here: 

http://www.artima.com/cla/contributorsLicenseAgreement.pdf

Please kindly print and email the signed CLA to cla@artima.com .

We're sorry for any inconvenient caused, we're looking into the automation of the process but unfortunately it is not there yet: 

https://github.com/scalatest/scalatest/issues/1275

We would like thank you again for your effort, we highly appreciate your contribution.

Thanks.

**Comment by giftig** [comment]
Unfortunately printing and rescanning the CLA would take considerably longer than the actual change, so closing this as I'm unlikely to ever fill that out.

**Pull request closed without merging**
