### PR TITLE
Pretty Differ

### PR DESCRIPTION
**Pull request by cheeseng**
Differ implementation that follows Prettifier way.

### CODE REVIEW

**Comment by kubum** [comment]
@cheeseng do you think it's going to be merged into 3.1? Do you plan to do more work on it? I would be very handy to have friendly difference messages.

**Comment by cheeseng** [comment]
@kubum We are still trying different approach to see which is the best, fyi I am working on the latest branch here: 

https://github.com/cheeseng/scalatest/tree/pretty-differ-3

Just want to assure you it is something that we would like to have, @bvenners will decide which version it should go in though.  :)

**Comment by kubum** [comment]
Hi @cheeseng 

How is it going? Did you find out what way is the best? Do you think you need some help on it?

**Comment by cheeseng** [comment]
@kubum unfortunately @bvenners still has not had chance to look at this yet, perhaps I'll have to rebase the branch first since it now conflicting to 3.1.x already, unfortunately.

**Comment by cheeseng** [comment]
Closing in favor of https://github.com/scalatest/scalatest/pull/1027 .

**Pull request closed without merging**
