### PR TITLE
Update to Scala 3.0.0-M2

### PR DESCRIPTION
**Pull request by nicolasstucki**
* Based on top of #1923
* Dotty PR: https://github.com/lampepfl/dotty/pull/10503

### CODE REVIEW

**Comment by cheeseng** [comment]
@nicolasstucki I notice there are now 6 tests failing (passed in 3.0.0-M1): 

```
> sbt scalatestTestDotty/test
...
[info] Run completed in 16 seconds, 600 milliseconds.
[info] Total number of tests run: 6313
[info] Suites: completed 310, aborted 0
[info] Tests: succeeded 6307, failed 6, canceled 7, ignored 8, pending 18
[info] *** 6 TESTS FAILED ***
...
[info] OldDocSpec:
[info] The stripMargin method 
[info] - when passed a string with leading space, should return the string with the leading space omitted *** FAILED *** (0 milliseconds)
[info]   "[ ]Howdy" did not equal "[]Howdy" (OldDocSpec.scala:181)
[info]   Analysis:
[info]   "[ ]Howdy" -> "[]Howdy"
[info] OldDocSpec:
[info] The stripMargin method 
[info] - when passed a string with leading space and two lines, should return the string with the leading space omitted from the first line, and the same amound omitted from the second line, with tabs converted to one space *** FAILED *** (0 milliseconds)
[info]   "[ Howdy
[info]   1]23456789" did not equal "[Howdy
[info]   ]23456789" (OldDocSpec.scala:189)
[info]   Analysis:
[info]   "[ Howdy
[info] 1]23456789" -> "[Howdy
[info] ]23456789"
[info] OldDocSpec:
[info] The stripMargin method 
[info] - when passed a string with one or more blank lines, a line with leading space and two lines, should return the string with the leading space omitted from the first line, and the same amound omitted from the second line, with tabs converted to one space *** FAILED *** (0 milliseconds)
[info]   "
[info]   [ Howdy
[info]   1]23456789" did not equal "
[info]   [Howdy
[info]   ]23456789" (OldDocSpec.scala:197)
[info]   Analysis:
[info]   "
[info] [ Howdy
[info] 1]23456789" -> "
[info] [Howdy
[info] ]23456789"
[info] DocSpecSpec:
[info] The stripMargin method 
[info] - when passed a string with leading space, should return the string with the leading space omitted *** FAILED *** (0 milliseconds)
[info]   "[ ]Howdy" did not equal "[]Howdy" (DocSpecSpec.scala:223)
[info]   Analysis:
[info]   "[ ]Howdy" -> "[]Howdy"
[info] DocSpecSpec:
[info] The stripMargin method 
[info] - when passed a string with leading space and two lines, should return the string with the leading space omitted from the first line, and the same amound omitted from the second line, with tabs converted to one space *** FAILED *** (0 milliseconds)
[info]   "[ Howdy
[info]   1]23456789" did not equal "[Howdy
[info]   ]23456789" (DocSpecSpec.scala:231)
[info]   Analysis:
[info]   "[ Howdy
[info] 1]23456789" -> "[Howdy
[info] ]23456789"
[info] DocSpecSpec:
[info] The stripMargin method 
[info] - when passed a string with one or more blank lines, a line with leading space and two lines, should return the string with the leading space omitted from the first line, and the same amound omitted from the second line, with tabs converted to one space *** FAILED *** (0 milliseconds)
[info]   "
[info]   [ Howdy
[info]   1]23456789" did not equal "
[info]   [Howdy
[info]   ]23456789" (DocSpecSpec.scala:239)
[info]   Analysis:
[info]   "
[info] [ Howdy
[info] 1]23456789" -> "
[info] [Howdy
[info] ]23456789"
[error] Failed tests:
[error]         org.scalatest.OldDocSpec
[error]         org.scalatest.DocSpecSpec
[error] (scalatestTestDotty / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 309 s (05:09), completed Nov 26, 2020 10:54:05 PM
```

Can you see if it is expected?

Anyway, I have staged 3.2.3 build for Scala 3.0.0-M2 using this PR, @bvenners will have the pleasure to release it.  :)

**Comment by nicolasstucki** [comment]
I had issues with the tests never finishing. Did they finish for you?

**Comment by cheeseng** [comment]
@nicolasstucki The tests did finish for me, though it did take some time to build before running.

**Comment by cheeseng** [comment]
@nicolasstucki Just in case SBT_OPTS matter, I have: 

```
export SBT_OPTS="-server -Xms512M -Xmx10G -Xss10M -XX:+UseConcMarkSweepGC -XX:NewRatio=8"
```

**Comment by nicolasstucki** [comment]
I did that but I got 
```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
```
maybe that is my issue

**Comment by nicolasstucki** [comment]
Now it seems to be working

**Comment by nicolasstucki** [comment]
I do not see any reason why those tests should have changed. Might be a bug.

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by liufengyun** [comment]
@cheeseng The last commit should fix the CI failure. Could you please confirm?

**Comment by cheeseng** [comment]
@liufengyun Sorry just saw your message now, it is a bit late over here, I'll try your fix in the morning tomorrow.

Cheers!

**Comment by cheeseng** [comment]
@liufengyun I tried it but unfortunately it failed to build with the following compile errors: 

```
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:218:52 
[error] 218 |      a [NullPointerException] should be thrownBy { stripMargin(null) }
[error]     |                                                    ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:221:6 
[error] 221 |      stripMargin("") should equal ("")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:224:6 
[error] 224 |      stripMargin(" Howdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:225:6 
[error] 225 |      stripMargin("  Howdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:226:6 
[error] 226 |      stripMargin("   Howdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:227:6 
[error] 227 |      stripMargin("\tHowdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:228:6 
[error] 228 |      stripMargin("\t\tHowdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:229:6 
[error] 229 |      stripMargin(" \t \tHowdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:232:6 
[error] 232 |      stripMargin(" Howdy\n123456789") should equal ("Howdy\n23456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:233:6 
[error] 233 |      stripMargin("  Howdy\n123456789") should equal ("Howdy\n3456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:234:6 
[error] 234 |      stripMargin("   Howdy\n123456789") should equal ("Howdy\n456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:235:6 
[error] 235 |      stripMargin("\tHowdy\n123456789") should equal ("Howdy\n23456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:236:6 
[error] 236 |      stripMargin("\t\tHowdy\n123456789") should equal ("Howdy\n3456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:237:6 
[error] 237 |      stripMargin(" \t \tHowdy\n123456789") should equal ("Howdy\n56789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:240:6 
[error] 240 |      stripMargin("\n Howdy\n123456789") should equal ("\nHowdy\n23456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:241:6 
[error] 241 |      stripMargin("\n  \n\n  Howdy\n123456789") should equal ("\n\n\nHowdy\n3456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:242:6 
[error] 242 |      stripMargin("\n  \t\t\n   Howdy\n123456789") should equal ("\n\t\nHowdy\n456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:243:6 
[error] 243 |      stripMargin("\n\n\n\n\tHowdy\n123456789") should equal ("\n\n\n\nHowdy\n23456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:244:6 
[error] 244 |      stripMargin("\n\t\tHowdy\n123456789") should equal ("\nHowdy\n3456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/DocSpecSpec.scala:245:6 
[error] 245 |      stripMargin("\n      \n \t \tHowdy\n123456789") should equal ("\n  \nHowdy\n56789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class DocSpecSpec
[error]     |and imported by name subsequently by import org.scalatest.DocSpec.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:176:52 
[error] 176 |      a [NullPointerException] should be thrownBy { stripMargin(null) }
[error]     |                                                    ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:179:6 
[error] 179 |      stripMargin("") should equal ("")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:182:6 
[error] 182 |      stripMargin(" Howdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:183:6 
[error] 183 |      stripMargin("  Howdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:184:6 
[error] 184 |      stripMargin("   Howdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:185:6 
[error] 185 |      stripMargin("\tHowdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:186:6 
[error] 186 |      stripMargin("\t\tHowdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:187:6 
[error] 187 |      stripMargin(" \t \tHowdy") should equal ("Howdy")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:190:6 
[error] 190 |      stripMargin(" Howdy\n123456789") should equal ("Howdy\n23456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:191:6 
[error] 191 |      stripMargin("  Howdy\n123456789") should equal ("Howdy\n3456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:192:6 
[error] 192 |      stripMargin("   Howdy\n123456789") should equal ("Howdy\n456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:193:6 
[error] 193 |      stripMargin("\tHowdy\n123456789") should equal ("Howdy\n23456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:194:6 
[error] 194 |      stripMargin("\t\tHowdy\n123456789") should equal ("Howdy\n3456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:195:6 
[error] 195 |      stripMargin(" \t \tHowdy\n123456789") should equal ("Howdy\n56789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:198:6 
[error] 198 |      stripMargin("\n Howdy\n123456789") should equal ("\nHowdy\n23456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:199:6 
[error] 199 |      stripMargin("\n  \n\n  Howdy\n123456789") should equal ("\n\n\nHowdy\n3456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:200:6 
[error] 200 |      stripMargin("\n  \t\t\n   Howdy\n123456789") should equal ("\n\t\nHowdy\n456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:201:6 
[error] 201 |      stripMargin("\n\n\n\n\tHowdy\n123456789") should equal ("\n\n\n\nHowdy\n23456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:202:6 
[error] 202 |      stripMargin("\n\t\tHowdy\n123456789") should equal ("\nHowdy\n3456789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[error] -- [E049] Reference Error: /home/cheeseng/git/scalatest/dotty/scalatest-test/target/scala-3.0.0-M2/src_managed/test/org/scalatest/OldDocSpec.scala:203:6 
[error] 203 |      stripMargin("\n      \n \t \tHowdy\n123456789") should equal ("\n  \nHowdy\n56789")
[error]     |      ^^^^^^^^^^^
[error]     |Reference to stripMargin is ambiguous,
[error]     |it is both defined in class OldDocSpec
[error]     |and imported by name subsequently by import org.scalatest.Doc.stripMargin
[warn] two warnings found
[error] 40 errors found
[error] (scalatestTestDotty / Test / compileIncremental) Compilation failed
```

I submitted the following PR to your branch here to fix them: 

https://github.com/dotty-staging/scalatest/pull/13

@nicolasstucki @liufengyun  Just trying to see If I understand it correctly, it is the cause is the stripMargin in the global scope now take precedence over the one imported at the top, is that right?

**Comment by liufengyun** [comment]
> @nicolasstucki @liufengyun Just trying to see If I understand it correctly, it is the cause is the stripMargin in the global scope now take precedence over the one imported at the top, is that right?

Thanks @cheeseng . Yes, it is due to that `this.stripMargin` (defined in `Assertions`) takes precedence over the imported one.

**Pull request merged**
