### PR TITLE
3.1.0-SNAP10

### PR DESCRIPTION
**Pull request by cheeseng**
Bumped up snap release version to 3.1.0-SNAP10.

### CODE REVIEW

**Comment by kailuowang** [comment]
I just added the 800th star for scalatest. Would that grant me the reward of knowing if there is an ETA for 3.1.0 release?  😸 😸 😸 

I don't meant to be pushy. A Scalatest 3.1.0 ETA will be very nice for the cats community, it will enable us to update Cats 2.0 ETA as well as its 2019 roadmap. Thanks!!

**Comment by cheeseng** [comment]
Closing to be re-open for Travis rebuild.

**Comment by cheeseng** [comment]
Re-opening for Travis rebuild.

**Comment by bvenners** [comment]
@kailuowang I am hoping to get 3.1.0 out by ScalaDays. We still have a few things to do to it, then go through an RC.

**Comment by kailuowang** [comment]
Thanks for the ETA @bvenners. Appreciate it.

**Pull request merged**
