### PR TITLE
Upgrade to Dotty 0.25.0-RC2

### PR DESCRIPTION
**Pull request by smarter**

### CODE REVIEW

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by smarter** [comment]
Note that I was not able to test these changes, I let `scalacticTestDotty/test:compile` run for > 30 minutes and it never finished, looking at stack traces it doesn't look like it was stuck in an infinite loop, so maybe some macros are generating a huge amount of code? This already happens on branch 3.2.x-new before this PR (is there no CI running in this repository?), but it does not happen in the older version of scalatest in our community-build which we patched to work with the latest dotty: https://github.com/dotty-staging/scalatest/commits/dotty-community-build, so something must have changed in the scalatest repository to cause dotty compile time to blow up.

**Comment by cheeseng** [comment]
@smarter Our CI currently only covers scala 2.x builds on jvm, I have been running scalacticTestDotty manually on my machine, and it is working fine where it took about 3mins to finish using Dotty 0.24.0.  I'll try this PR and see if I can reproduce what you're encountering locally.

**Comment by cheeseng** [comment]
@smarter Fyi This PR did finish on my machine, took about 3 mins also, I am not sure why it didn't finish on your end, for communication this is how I built: 

```
> sbt scalatestTestDotty/clean scalacticTestDotty/clean scalatestDotty/clean scalacticDotty/clean
> sbt scalatestTestDotty/test
> sbt scalacticTestDotty/test
```

They are all green (and finished) when I ran the above.

**Comment by smarter** [comment]
Thanks for checking! That's very weird then, would be good to get a third person to run it and see what happens, @nicolasstucki could you try running `scalacticTestDotty/test` on scalatest master ?

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by nicolasstucki** [comment]
It also took around 3 minutes on my machine  for `scalatest:3.2.x-new` and `dotty-staging:dotty-3.2`. All tests passed.

**Pull request merged**
