### PR TITLE
3.2.12 Release

### PR DESCRIPTION
**Pull request by cheeseng**
Adjusted for 3.2.12 release.

### CODE REVIEW

**Comment by catap** [comment]
@cheeseng any news here?

**Comment by cheeseng** [comment]
> @cheeseng any news here?

I have staged all artifacts for 3.2.12, @bvenners shall have the pleasure to release them.  :)

**Comment by catap** [comment]
@cheeseng / @bvenners I guess `3.2.12` is broken at least for `3.0.x` scala. An attempt to use it leads to error:
```
[error] error while loading $throws$package$,
[error] class file scala/runtime/$throws$package.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
[error] TASTy signature has wrong version.
[error]  expected: {majorVersion: 28, minorVersion: 0}
[error]  found   : {majorVersion: 28, minorVersion: 1}
[error] 
[error] This TASTy file was produced by a more recent, forwards incompatible release.
[error] To read this TASTy file, please upgrade your tooling.
[error] The TASTy file was produced by Scala 3.1.0-bin-nonbootstrapped.
```

**Comment by catap** [comment]
Unfortunately `3.1.x` isn't binary compatible for `3.0.x` [details](https://www.scala-lang.org/blog/2021/10/21/scala-3.1.0-released.html) and an easy way since `3.1.2` is released is using `ThisBuild / scalaOutputVersion` or similar things as [suggested here](https://www.scala-lang.org/blog/2022/04/12/scala-3.1.2-released.html).

**Comment by catap** [comment]
@cheeseng here a fix for this branch: https://github.com/cheeseng/scalatest/pull/5

But I not sure that you can replace `3.2.12` artifacts, probably a release of `3.2.13` required.

**Review by bvenners — APPROVED** [review]

**Pull request merged**
